# Word Hero Web Application Configuration
server:
  port: 8080
  host: "localhost"

# Application settings
app:
  name: "Word Hero"
  page_size: 25
  excel_file: "configs/words/IELTS.xlsx"

# Logging settings
logging:
  level: "info"
  file: ""