# Word Hero Web Application Configuration
server:
  port: 8080
  host: "localhost"

# Application settings
app:
  name: "Word Hero"
  page_size: 25
  static_dir: "web/static"
  excel_file: "configs/words/IELTS.xlsx"

# Database settings
database:
  host: "192.168.132.128"
  port: 5432
  user: "postgres"
  password: "postgres"
  dbname: "word_hero"
  ssl_mode: "disable"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

# JWT settings
jwt:
  secret: "your-secret-key-change-in-production"
  expires_in: "24h"

# Logging settings
logging:
  level: "info"
  file: ""